version: '3.5'

services:

  moodle_php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile81
    image: moodlelocal/php81:v1
    container_name: moodle_php
    volumes:
      - ./src/:/var/www/html/
      - ./moodledata/:/var/www/html/moodledata/
    networks:
      - moodleshared

  moodle_php_cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile81
    image: moodlelocal/php81_cli:v1
    container_name: moodle_php_cli
    volumes:
      - ./src/:/var/www/html/
      - ./moodledata/:/var/www/html/moodledata/
    networks:
      - moodleshared
