version: '3.5'

services:

  moodle_php:
    environment:
      - "MOODLE_DOCKER_BROWSER=chrome"

  moodle_php_cli:
    environment:
      - "MOODLE_DOCKER_BROWSER=chrome"

  selenium:
    image: "selenium/standalone-chrome-debug:2.53.1"
    ports:
      - "127.0.0.1:5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      # Workaround for https://github.com/SeleniumHQ/docker-selenium/issues/227
      "no_proxy": localhost